version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
       - 5672:5672
       - 15672:15672
    volumes:
       - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
  #citywork.services.product.api:
  #  image: ${DOCKER_REGISTRY-}cityworkservicesproductapi
  #  build:
  #    context: .
  #    dockerfile: src/Services/Product/CityWork.Services.Product.API/Dockerfile
volumes:
  rabbitmqdata: