global:
  scrape_interval:     15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "Product"
    scrape_interval: 5s
    static_configs:
    - targets: ["127.0.0.1:7207"]
    scheme: https